name: Monty B
favicon: null
layout_spectrum: 0.40986419725231826
typography_spectrum: 0.3348686380777508
title: "Dreary veils and deep sorrow. Entertainment at it's best."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#006d8e'
    - '#ced5db'
    - '#6fb9d6'
    - '#505c68'
  brandStrength: 0.9037232890259475
  lightness: 0.7148470811080188
  saturation: 0.5918249629903585
  rhythmicContrast: 0.38244197028689086
purpose: []
